version: '3.8'

services:
  tutor-db:
    image: postgres
    ports:
      - '5432:5432'
    container_name: tutor-db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - tutorapp-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --loglevel warning
    networks:
      - tutorapp-network

volumes:
  redis_data:
    
networks:
  tutorapp-network:
    driver: bridge


