version: '3.8'

services:
  tutor-db:
    image: postgres
    ports:
      - '5432:5432'
    container_name: tutor-db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - tutorapp-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /root/devs-diploma-project:/var/www/html/
      - ./app.conf:/etc/nginx/conf.d/
    networks:
      - tutorapp-network

networks:
  tutorapp-network:
    driver: bridge

