# Generated by Django 5.0.1 on 2024-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Женщина', 'Женщина'), ('Мужчина', 'Мужчина')], null=True),
        ),
    ]
