# Generated by Django 5.0.1 on 2024-02-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
