# Generated by Django 5.0.1 on 2024-02-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0004_customuser_is_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_tutor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=250),
            preserve_default=False,
        ),
    ]
