# Generated by Django 5.0.1 on 2024-03-11 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0004_emailcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='user',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('level', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('category_id', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='tutorapp.category')),
                ('teacher_id', models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
