# Generated by Django 5.0.1 on 2024-03-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0005_alter_emailcode_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Math', 'Math'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Languages', 'Languages')], max_length=250),
        ),
    ]
