# Generated by Django 5.0.1 on 2024-02-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0006_alter_customuser_email_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student_id',
        ),
    ]
