# Generated by Django 5.0.1 on 2024-03-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0006_alter_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.CharField(choices=[('Больше', 'Больше'), ('От 3 года до 5 лет', 'От 3 года до 5 лет'), ('До 3 лет', 'До 3 лет'), ('Нет опыта', 'Нет опыта')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=250),
        ),
    ]
