# Generated by Django 5.0.1 on 2024-03-15 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0007_remove_customuser_name_remove_customuser_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Database Management', 'Database Management'), ('Graphic Design and Multimedia', 'Graphic Design and Multimedia'), ('Finance and Economics', 'Finance and Economics'), ('Networking and Security', 'Networking and Security'), ('Mathematics and Statistics', 'Mathematics and Statistics'), ('Web Development', 'Web Development'), ('Shell Scripting and Linux', 'Shell Scripting and Linux'), ('Functional Programming', 'Functional Programming'), ('Game Development', 'Game Development'), ('History and Social Studies', 'History and Social Studies'), ('Mobile App Development', 'Mobile App Development')], max_length=250),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(max_length=250)),
                ('end_date_time', models.DateTimeField(max_length=250)),
                ('course_id', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='tutorapp.course')),
            ],
        ),
    ]
