# Generated by Django 5.0.1 on 2024-03-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0008_course_cost_alter_category_category_name_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
