# Generated by Django 5.0.1 on 2024-02-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0008_remove_teacher_email_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='country',
            field=models.CharField(max_length=250),
        ),
    ]
