# Generated by Django 5.0.1 on 2024-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0009_remove_teacher_profile_picture_alter_teacher_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
