# Generated by Django 5.0.1 on 2024-03-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0010_coursestudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursestudent',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursestudent',
            old_name='student_id',
            new_name='student',
        ),
    ]
