# Generated by Django 5.0.1 on 2024-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0012_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
