# Generated by Django 5.0.1 on 2024-03-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0013_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursestudent',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='coursestudent',
            old_name='student',
            new_name='student_id',
        ),
    ]
