# Generated by Django 5.0.1 on 2024-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0014_category_remove_users_role_id_customuser_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='education',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_year',
            field=models.CharField(choices=[('От 1 года до 3 лет', 'От 1 года до 3 лет'), ('1 год', '1 год'), ('Нет опыта', 'Нет опыта')], default=12.12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], default=12.12, max_length=20),
            preserve_default=False,
        ),
    ]
