# Generated by Django 5.0.1 on 2024-03-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0015_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
