# Generated by Django 5.0.1 on 2024-02-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0015_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
