# Generated by Django 5.0.1 on 2024-03-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0021_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.CharField(choices=[('Больше', 'Больше'), ('От 3 до 5 лет', 'От 3 до 5 лет'), ('До 3 лет', 'До 3 лет'), ('Нет опыта', 'Нет опыта')], null=True),
        ),
    ]
