# Generated by Django 5.0.1 on 2024-04-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0030_videoconference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
